### ISSUE TITLE
run.sh y Openshift

### ISSUE THREAD

**Issue by profesorasix** [TrabajoFinal/ProyectoFinal#1]
Hola,
Varias cosas.
- Falta el fichero _run.sh_
- El directorio Openshift no debe existir, es el directorio oculto _.openshift_ el que debe estar

**Comment by shaheershahzad** [comment]
El fichero run.sh ha sido creado y el directorio Openshift también se ha añadido como oculto.
Después de haber hecho todos los pasos encontrados en internet y haber creado la aplicación en Openshift, a la hora de ir a la página web me da error. A ver si le puedes echar un vistazo al código y encontrar el fallo.
